# Generated by Django 3.2 on 2023-04-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230412_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('moderator', 'moderator'), ('admin', 'admin'), ('user', 'user')], default='user', max_length=50, verbose_name='Роль'),
        ),
    ]
